[package]
name = "artemyarulin/pjdfstest"
version = "0.1.0"
description = "pjdfstest runner UI"
readme = "README.md"
entrypoint = "http"

[dependencies]
"wasmer/bash" = "*"

[fs]
"/app" = "package-assets/app"
"/wasix" = "package-assets/wasix"

[[module]]
name = "client-http"
source = "target/wasm32-wasmer-wasi/release/client-http.rustc.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[module]]
name = "client-cli"
source = "target/wasm32-wasmer-wasi/release/client-cli.rustc.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[module]]
name = "pjdfstest"
source = "target/wasm32-wasmer-wasi/release/pjdfstest.rustc.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[module]]
name = "uname"
source = "target/wasm32-wasmer-wasi/release/uname.rustc.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.1.0-unstable"

[[command]]
name = "http"
module = "client-http"
runner = "wasi"

[command.annotations.wasi]
env = ["PATH=/wasix:/usr/bin:/bin"]

[[command]]
name = "client-cli"
module = "client-cli"
runner = "wasi"

[command.annotations.wasi]
env = ["PATH=/wasix:/usr/bin:/bin"]

[[command]]
name = "uname"
module = "uname"
runner = "wasi"
